### ISSUE TITLE
Switch to React

### ISSUE THREAD

**Issue by sskhandek** [HackIllinois/admissions-2017#3]

**Comment by bluedrops** [comment]
![mmh](https://cloud.githubusercontent.com/assets/14851163/22866714/8b230cee-f140-11e6-9160-d3fa28dfbc7f.png)

**Comment by nickofbh** [comment]
Assigned to @bluedrops

**Comment by sskhandek** [comment]
![](http://arsenalfordemocracy.com/wp-content/uploads/2014/03/obama-nuclear-heckle-reaction.gif)
