### ISSUE TITLE
Simon's on fire

### ISSUE THREAD

**Issue by sskhandek** [HackIllinois/admissions-2017#4]
<img width="1104" alt="screen shot 2017-02-12 at 4 32 45 pm" src="https://cloud.githubusercontent.com/assets/5349493/22866750/ef5796b2-f140-11e6-901f-aaa230704ab1.png">

**Comment by bluedrops** [comment]
![fire](https://cloud.githubusercontent.com/assets/14851163/22866771/3bedaa2a-f141-11e6-96c0-156a4aa59623.gif)
